### PR TITLE
NO MRG, TST, MNT: Re-rendered with conda-smithy 2.0.1.post.dev5

### PR DESCRIPTION
**Pull request by jakirkham**
Re-render to test fast finishing CI's PR builds.

xref: https://github.com/conda-forge/conda-smithy/pull/455

### CODE REVIEW

**Comment by jakirkham** [comment]
Below is a listing showing failing outdated builds for each CI on this PR and passing latest builds for each CI on this PR. These demonstrate this is working correctly.

* CircleCI
  * [Outdated]( https://circleci.com/gh/conda-forge/conda-forge-build-setup-feedstock/162 )
  * [Latest]( https://circleci.com/gh/conda-forge/conda-forge-build-setup-feedstock/163 )
* Travis CI
  * [Outdated]( https://travis-ci.org/conda-forge/conda-forge-build-setup-feedstock/builds/200946939 )
  * [Latest]( https://travis-ci.org/conda-forge/conda-forge-build-setup-feedstock/builds/200946960 )
* AppVeyor
  * [Outdated]( https://ci.appveyor.com/project/conda-forge/conda-forge-build-setup-feedstock/build/1.0.178 )
  * [Latest]( https://ci.appveyor.com/project/conda-forge/conda-forge-build-setup-feedstock/build/1.0.179 )

Edit: Updated the links as Travis CI's status did not show up correctly on the PR. So did a fresh test.

**Comment by scopatz** [comment]
LGTM

**Comment by jakirkham** [comment]
Oh, this isn't suppose to be merged. This merely exists in order to test PR ( https://github.com/conda-forge/conda-smithy/pull/455 ), which allows us to re-render with this functionality included.

**Comment by scopatz** [comment]
I see :)

**Comment by jakirkham** [comment]
Actual re-rendering can be found in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/56 ).

**Pull request closed without merging**
