### PR TITLE
Fast finish CIs script

### PR DESCRIPTION
**Pull request by jakirkham**
This adds a script for fast finish CI builds. The script is designed to work on CircleCI, Travis CI, and AppVeyor. It checks to see if the current build has the highest build ID (number) out of all builds for the PR. If it doesn't have the highest build ID, then the job errors itself out. If it does have the highest build number or is not a PR, the job proceeds without issues.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/core @goanpeca

**Comment by bgruening** [comment]
Tested in BioConda and it seems to work for us as well :)
Thanks!

**Comment by jakirkham** [comment]
Also thanks to @tkelman for his work on these problems.

**Comment by SylvainCorlay** [comment]
@jakirkham in the situation where a PR comes on the top of another one, will the build of the earlier PR be cancelled?

**Comment by jakirkham** [comment]
IIUC you are considering a situation like PR ( https://github.com/conda-forge/zeromq-feedstock/pull/13 ) and PR ( https://github.com/conda-forge/zeromq-feedstock/pull/14 ), which share common history and are opened one after another? No, it will not cancel the builds in PR ( https://github.com/conda-forge/zeromq-feedstock/pull/13 ) when PR ( https://github.com/conda-forge/zeromq-feedstock/pull/14 ) is opened. Travis CI shows them as builds under different PRs. So we ignore them. AFAICT the only reason the status from PR ( https://github.com/conda-forge/zeromq-feedstock/pull/13 ) will show up on a commit in PR ( https://github.com/conda-forge/zeromq-feedstock/pull/14 ) is because GitHub views statuses as tied to a particular commit.

**Comment by patricksnape** [comment]
Looks great to me - I would say this is a good start and we can muse on dependent builds later

**Comment by jakirkham** [comment]
IMHO letting different PR's builds run is an ok thing (even if they share history) and not a problem worth fixing.

**Comment by jakirkham** [comment]
FYI will be out next week and may not be able to come back to this right away when I get back. So if it seems acceptable, maybe we should just merge this so we can make the need tweaks to `staged-recipes` and `conda-smithy` to get this into production.

**Comment by scopatz** [comment]
I think this needs documentation of some kind. Even a docstring at the top of the module explaining what its purpose for existing is.

**Comment by bsipocz** [comment]
@jakirkham et al - This script is not needed for travis as they have an option for this in their setup. We use it in many astropy projects as it works fine https://github.com/conda-forge/staged-recipes/issues/2272
The advantage to have this switched on is that it cancels the now obsolete build straight away and removes it from the queue, while running this script still needs the job to start up.
Hope it helps, I can help but noticing the enormous queue time for conda-forge projects.

**Comment by jakirkham** [comment]
While I have heard this is planned by Travis CI, I still do not see this setting on any of our repos. Further we lack any kind of stable API to enable it on existing feedstocks or new feedstocks that we would create. Given it will take some time to see either of these things, this script remains quite valuable for Travis CI.

In addition, there is the question of whether this feature behaves the way we wish or has some unintended side effects or lingering bugs. In either case, we have no control over these potential problems with Travis CI's feature unlike this script, which is totally open and free to change as needed. Even if Travis CI's feature mostly works fine, it is nice to have a fallback for when it doesn't. Not to mention this script works not just on Travis CI, but AppVeyor and CircleCI. There is already code shared between these cases and with some massaging it is possible to expand on this.

**Comment by jakirkham** [comment]
> I think this needs documentation of some kind. Even a docstring at the top of the module explaining what its purpose for existing is.

There is a help string in the CLI and each of the arguments are explained. Could you please clarify what you would like to see, @scopatz? Perhaps even the exact wording.

If I have time and some clarification on this, I might even be able to fix it today. However, if not, this may sit dormant for a couple of weeks more. In which case, I urge us to merge this and send follow-up PRs to fix it instead.

**Comment by jakirkham** [comment]
For reference, this is what it prints as help now.

```
usage: ff_ci_pr_build.py [-h] [-v] --ci {circle,travis,appveyor} repo bld [pr]

Determine whether this build should end.

positional arguments:
  repo                  GitHub repo name (e.g. `user/repo`.)
  bld                   CI build number for this pull request
  pr                    GitHub pull request number of this build

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Whether to include output
  --ci {circle,travis,appveyor}
                        Which CI to check for an outdated build
```

**Comment by scopatz** [comment]
> There is a help string in the CLI and each of the arguments are explained. Could you please clarify what you would like to see, @scopatz? Perhaps even the exact wording.

My issue is that - even with the help message - I still don't understand the the motivation of script, in what context it should be run, who should run it, etc. My claim is that I couldn't write the docs even if I wanted too, because I am missing critical pieces of information. Most of conda-forge is this way (minimal to low documentation). I don't think it is maintainable and I'd like to see it more maintainable.  

Just a few sentences about the intended purpose and motivation are all that is needed. The value of this, I argue, is that this is a key way to identify bugs when they arise. If only the implementation exists, how do you know what the code *should* be doing. How does a new person, who suspects it is broken, go about fixing it?

I'd like to see conda-forge grow to new developers and maintainers. One of the keys things I think we need to do as a community is provide a learning curve rather than a brick wall.  So if I have trouble intuiting something after a review, I take that as a clear barrier to entry for any new potential devs.  I hope this helps.

**Comment by jakirkham** [comment]
I appreciate the need for documentation. We could probably have a longer conversation about the challenges we face with that in conda-forge and how we can work to improve that.

That being said, I'm still unclear what documentation needs to be added to address this request. There seems to be ample explanation in the commit messages, PRs, and comments. I remain unclear what of the aforementioned information is relevant/needed here. If you could simply provide the wording you would like to see, I can add it. Anything beyond that I simply lack the time to do.

**Comment by scopatz** [comment]
I think copying the commit message(s, they seem to be mostly the same) and/or the original post into a module-level docstring would be fine. Commit messages and issue/pr conversations don't count as documentation to me, so perhaps that is where some of the discrepancy lies.

**Comment by jakirkham** [comment]
I agree with you completely. Was mainly trying to come to consensus on what constituted good documentation before digging into it.

Have tweaked the wording from one of the commits and added it as the file level docstring. Also have updated the help description to be the first line of that docstring. Please let me know if this is ok.

**Comment by scopatz** [comment]
Looks great to me, thanks @jakirkham!

**Comment by jakirkham** [comment]
Thanks @scopatz. @jjhelmus, could you please also review this?

Edit: Asking as you had helped review the original PR ( https://github.com/conda-forge/staged-recipes/pull/2257 ) as well.

**Comment by jakirkham** [comment]
I know I asked for another review, but am a little tempted to get this merged this weekend while Travis CI is not so backlogged. We can always tweak this more in the future. Anyone feel like merging?

**Comment by scopatz** [comment]
thanks!

**Comment by jakirkham** [comment]
Meant to merge, right? 😉

**Comment by scopatz** [comment]
Oh yeah, whoops. was on my phone :(

**Comment by jakirkham** [comment]
No worries. Thanks @scopatz.

**Pull request merged**
