### PR TITLE
Custom MAKEFLAGS for Linux builds

### PR DESCRIPTION
**Pull request by jschueller**
supersedes https://github.com/conda-forge/toolchain-feedstock/pull/6

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @jschueller. This seems sensible to me. @pelson, thoughts?

**Comment by pelson** [comment]
:+1:

**Comment by jschueller** [comment]
@jakirkham, this doesn't seem to be work, I cannot see MAKEFLAGS in by builds, to I have to specify something in my recipes manually ? Or do I have to wait for a tag or something to be included ?

**Comment by jakirkham** [comment]
That's because we are not using this yet. It is our plan to switch over to it, but we are not there yet.

**Comment by jschueller** [comment]
@jakirkham, ok, thanks

**Comment by jakirkham** [comment]
Removal is being proposed in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/18 ). Maybe we can look at overriding `CPU_COUNT` with `conda-build`. That might give us the healthy balance.

Proposed to `conda-build` in issue ( https://github.com/conda/conda-build/issues/1117 ).

**Pull request merged**
