### PR TITLE
Fix conda-build >= 2.0.0 bug, closes #28

### LINKED ISSUE #28: Upload script fails with conda_build >= 2.0.0
Copied from conda-forge/conda-smithy#282

conda build version 2.0.0 changed the call signature of the [`bldpkg_path()` function](https://github.com/conda/conda-build/commit/cd2f45ccc4e984dd1b9ec05b71c4ee3317ff4d23) so that it now takes a second `config` argument.  This breaks the `upload_or_check_non_existence.py` script in conda-smithy, see conda-forge/doctr-feedstock#5.

A temporary fix which pins `conda-build` to 1.x was made in #27 but should be reverted once the upload script is updated to account for this new call signature.

### PR DESCRIPTION
**Pull request by basnijholt**
Fixes https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/28

See #28. I just copy pasted what was suggested by @jjhelmus [here](https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/28#issuecomment-243856570).

### CODE REVIEW

**Comment by patricksnape** [comment]
@jakirkham @jjhelmus Is this the correct fix for conda-build 2.0?

**Comment by jjhelmus** [comment]
I believe it is but I would invert the logic so that try uses the new call signature and the fallback is the `1.x` signature.  This would make it easier to change in the future when conda build 1.x is no longer a concern.

**Comment by basnijholt** [comment]
> I would invert the logic 

I changed it in ab73fda

**Comment by jakirkham** [comment]
Could you please bump the version? Guessing `3.2.1` makes sense. Need to merge/rebase with `master` first.

**Comment by jakirkham** [comment]
Any chance to make this minor change, @basnijholt? Then will be happy to merge.

**Comment by basnijholt** [comment]
Done :)

**Comment by jakirkham** [comment]
Hmm...says it has merge conflicts on GitHub. 😕

**Comment by basnijholt** [comment]
I'll fix it.

**Comment by basnijholt** [comment]
Sorry, that got really ugly there. But it is solved anyways.

Should I rewrite the history a bit?

**Comment by jakirkham** [comment]
Sure whatever works is fine with me. Maybe a rebase?

**Pull request closed without merging**
