### PR TITLE
Workaround conda-build ProgramFiles KeyError bug

### PR DESCRIPTION
**Pull request by jakirkham**
This pins `conda-build` to 1.21.5 on Windows to workaround issue ( https://github.com/conda/conda-build/issues/1130 ).

cc @msarahan @mwcraig @ocefpaf @patricksnape @pelson

### CODE REVIEW

**Comment by msarahan** [comment]
I think this probably only affects conda-build-all.  Not sure if that makes
you want to limit the scope of the pinning to only staged recipes.  Anyway,
I'll try to get a new tag out soon.

**Comment by jakirkham** [comment]
Honestly I don't love having to handle these pinnings in multiple places. That has been pretty time consuming and hard to track/revert. I'm happy enough to pin it here and wait for a bug fix.

**Comment by pelson** [comment]
> I'm happy enough to pin it here and wait for a bug fix.

To be clear, it is perfectly reasonable for @msarahan to call this a conda-build-all bug. The contract has always been clear about conda-build being a CLI only interface (for now). @msarahan, just to get your take on this, should I get beavering away on a conda-build-all fix or is this a genuine conda-build bug that could be seen without conda-build-all?

**Comment by ocefpaf** [comment]
Just to provide a data point here I saw this bug in https://github.com/conda-forge/staged-recipes/pull/1111#issuecomment-234246070 when sending it to staged-recipes. However, in the feedstock (https://github.com/conda-forge/humanfriendly-feedstock/pull/1) things worked.

I lost track of how and where versions are pinned to track this down now. But since this was not merged yet I don't think this pin is needed (b/c conda-build-all is not used there?).

**Comment by msarahan** [comment]
@pelson, I'd say do not fix conda-build-all.  It is a fair amount of work to convert it to use the CLI, and that work will all be worthless soon with the python api.

I think the fix is simple: https://github.com/conda/conda-build/pull/1135

Rather than any fix to conda-build-all, I would instead appreciate help testing that fix.  Perhaps modifying the CI scripts to install conda-build from source would be sufficient:

```
git clone https://github.com/msarahan/conda-build
cd conda-build && git checkout consolidate_bin_prepend && python setup.py install && cd ..
```

**Comment by jakirkham** [comment]
I think this is probably unneeded, but I would like to test it on something that needed this pinning. PR ( https://github.com/conda-forge/staged-recipes/pull/1123 ) seems like a good test case.

**Comment by jakirkham** [comment]
This has been [demonstrated](https://github.com/conda-forge/staged-recipes/pull/1123#issuecomment-234767946) to no longer be needed. Closing.

**Pull request closed without merging**
