### PR TITLE
downgrade conda-build to 1.20.1

### PR DESCRIPTION
**Pull request by ocefpaf**
1.20.2 did not work. Let's try 1.20.1 (no need to bump the build number as I removed the bad builds. Bad practice, but I don't want these to propagate beyond my tests here.)

### CODE REVIEW

**Comment by jakirkham** [comment]
Could we please correct the version number then?

**Comment by ocefpaf** [comment]
Let me fix the problem first. We created a bureaucratic problem here by making the configuration a package. It is really cumbersome now to do simple tests... I really prefer the old setup.

**Comment by jakirkham** [comment]
If you need to do testing, I would recommend doing the pinnings manually after the script is run in CI. This way you have a better idea of knowing if this is going to work or not before changing it here.

**Comment by ocefpaf** [comment]
We'll do that next time. Right now I need to test this in 3 different PRs and this is faster.

**Pull request merged**
