### PR TITLE
Pin conda-build to 1.21.7 to resolve *.pyc compilation issues.

### PR DESCRIPTION
**Pull request by jakirkham**
We have been encountering some `*.pyc` compilation issues as described in issue ( https://github.com/conda/conda-build/issues/1167 ). It seems this has been fixed in `master`, but has not been released. This is a temporary pinning that should be removed as soon as a new release is made.

cc @scopatz @megies @ocefpaf @pelson @msarahan

### CODE REVIEW

**Comment by msarahan** [comment]
1.21.11 is tagged: https://github.com/conda/conda-build/releases/tag/1.21.11 - builds should be available soon.  Pin this if you feel you need to, but I think you're just creating more work at this point.

**Comment by jakirkham** [comment]
Yeah, I made it before I saw you tagged it.

**Comment by jakirkham** [comment]
Seems `conda-build` version `1.21.11` is out. Closing...

**Comment by scopatz** [comment]
Thanks for fixing this in 1.21.11 @msarahan!

**Comment by msarahan** [comment]
No problem.  Happy to help where I can.

**Pull request closed without merging**
